### ISSUE TITLE
Import error for libdmtx package

### ISSUE THREAD

**Issue by HripsimeS** [openmv/libdmtx#1]
@iabdalkader @kwagyeman Hello.

I have to check and run an app on Android Studio and there is one Java file that has the following lines
**import org.libdmtx.DMTXImage
import org.libdmtx.DMTXTag**

For these both lines I got **package org.libdmtx does not exist** error message and then buidling of app is terminating.
Can you let me know why it does not import **libdmtx** package and how I can install it via android studio terminal?

Look forward to hearing from you!

**Comment by kwagyeman** [comment]
I have no idea why you are posting on our GitHub about an issue with the main library.
